### ISSUE TITLE
Problem with _fileio on st2 and linux

### ISSUE THREAD

**Issue by tosher** [packagecontrol/requests#1]
Old problem with requests on linux and st2:

<pre>
File "./some_module.py", line 24, in module
    import requests
File "/home/adminuser/.config/sublime-text-2/Packages/requests/all/requests/__init__.py", line 58, in module
    from . import utils
File "/home/adminuser/.config/sublime-text-2/Packages/requests/all/requests/utils.py", line 15, in module
    import io
File ".\io.py", line 63, in module

ImportError: No module named _fileio
</pre>

**Comment by FichteFoll** [comment]
Nothing that we could do about it. This module is very core to how requests functions. This needs to be fixed on Sublime Text's part.

What is your linux distro & its version & your installed python version?

**Comment by tosher** [comment]
Ubuntu 14,04 LTS with python 2.7.6, but it's not insteresting because of I need this for my plugin [Mediawiker](https://github.com/tosher/Mediawiker). Current version based on old version of mwclient and i'm trying to move it on actual release (https://github.com/mwclient/mwclient) with some changes for py3 compatibility.
But current versions using **requests**... eh.

**Comment by tosher** [comment]
https://github.com/codexns/sublime-fileio
